### ISSUE TITLE
Open shift unit test fails

### ISSUE THREAD

**Issue by garethahealy** [Hawkular-QE/hawkular-java-client#38]
(org.hawkular.client.test.metrics.openshift.MetricDefinitionTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.NullPointerException
    at org.hawkular.client.test.metrics.openshift.MetricDefinitionTest.verifyMetricDefinitionForPod(MetricDefinitionTest.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
    at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Server response: {"errorMsg":"Invalid tags: Tags[tags={pod_namespace=default, container_name=hawkular-metrics}]"}

**Comment by garethahealy** [comment]
Partial fix: https://github.com/garethahealy/hawkular-client-java/commit/123ef209d46316dfe906130afa966e68868ff671

**Comment by garethahealy** [comment]
@jotak @pilhuhn @jkandasa are the OpenShift tests needed inside the java client?

They currently fail and disabled on travis builds. I feel they are already covered by other tests, as per the below:

[1] https://github.com/hawkular/hawkular-client-java/blob/master/src/test/java/org/hawkular/client/test/metrics/openshift/CollectionRateDetailTest.java#L68 -> https://github.com/hawkular/hawkular-client-java/blob/master/src/test/java/org/hawkular/client/test/metrics/GaugeTest.java#L254-L266

[2] https://github.com/hawkular/hawkular-client-java/blob/master/src/test/java/org/hawkular/client/test/metrics/openshift/MetricDefinitionTest.java#L68 -> https://github.com/hawkular/hawkular-client-java/blob/master/src/test/java/org/hawkular/client/test/metrics/MetricTest.java#L100-L117

Any objections to removing?

**Comment by jotak** [comment]
I've searched a bit, and couldn't find where metrics are supposed to be created (for test MetricDefinitionTest). Maybe the test was initially running against an existing OS installation? Which would definitely not be the right way to proceed... So +1 for removing, it's the destiny of dead code :)

**Comment by jkandasa** [comment]
@garethahealy OS test code was introduced by @vnugent 
My opinion, we can remove OS unit test code. As this is generic Hawkular REST java client.

@vnugent Do we need OS unit test in Hawkular java client?

**Comment by vnugent** [comment]
The OpenShift tests were running against an existing cluster.  Feel free to remove/update as you see fit.
