### ISSUE TITLE
AvailabilityMetricTest fails due to cast issue

### ISSUE THREAD

**Issue by garethahealy** [Hawkular-QE/hawkular-java-client#39]
Metric returns text value for AvailabilityType, unable to construct model from that value:

com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of org.hawkular.metrics.model.AvailabilityType from String value 'unknown': value not one of declared Enum instance names: [AvailabilityType{code=0, text=up}, AvailabilityType{code=1, text=down}, AvailabilityType{code=2, text=unknown}, AvailabilityType{code=3, text=admin}]
 at [Source: [{"timestamp":1470934482950,"value":"unknown"},{"timestamp":1470934452950,"value":"up"},{"timestamp":1470934422950,"value":"down"}]; line: 1, column: 28](through reference chain: java.util.ArrayList[0]->org.hawkular.metrics.model.DataPoint["value"])
    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:883) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:117) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:72) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:18) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithErrorWrapping(BeanDeserializer.java:461) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564) ~[jackson-databind-2.5.4.jar:2.5.4]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618) ~[jackson-databind-2.5.4.jar:2.5.4]
    at org.hawkular.client.ClientResponse.<init>(ClientResponse.java:126) [classes/:?]
    at org.hawkular.client.ClientResponse.<init>(ClientResponse.java:69) [classes/:?]
    at org.hawkular.client.metrics.MetricsClientImpl.findAvailabilityData(MetricsClientImpl.java:142) [classes/:?]
    at org.hawkular.client.metrics.MetricsClientImpl.findAvailabilityData(MetricsClientImpl.java:147) [classes/:?]
    at org.hawkular.client.test.metrics.AvailabilityMetricTest.getData(AvailabilityMetricTest.java:77) [test-classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86) [testng-6.9.10.jar:?]
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643) [testng-6.9.10.jar:?]
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820) [testng-6.9.10.jar:?]
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128) [testng-6.9.10.jar:?]
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) [testng-6.9.10.jar:?]
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) [testng-6.9.10.jar:?]
    at org.testng.TestRunner.privateRun(TestRunner.java:782) [testng-6.9.10.jar:?]
    at org.testng.TestRunner.run(TestRunner.java:632) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunner.run(SuiteRunner.java:268) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.9.10.jar:?]
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.9.10.jar:?]
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244) [testng-6.9.10.jar:?]
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169) [testng-6.9.10.jar:?]
    at org.testng.TestNG.run(TestNG.java:1064) [testng-6.9.10.jar:?]
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74) [testng-plugin.jar:?]
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124) [testng-plugin.jar:?]

**Comment by garethahealy** [comment]
Fixed: https://github.com/garethahealy/hawkular-client-java/commit/fdd5e376b3d6a19a4fd4b6f985cb7770468120e9
